# Generated by Django 3.0.5 on 2020-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
