# Generated by Django 3.0.5 on 2020-04-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200416_0612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
